#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }
if [ "X${EUID}" != "X0" ]; then vecho "Skipped. Reason: no root privileges."; exit 0; fi;

USERHOMEDIR="$(getent passwd ${S6_USER:-alpine} | cut -d: -f6)";
MAVEN_CONFIG="${MAVEN_CONFIG:-$USERHOMEDIR/.m2}";

# ensure configuration dirs
vecho "Ensure configuration directories exist.";
mkdir -p \
    "${MAVEN_CONFIG}"
    ;

# fix permissions
vecho "Fixing permissions.";
chown ${S6_USER:-alpine}:${PGID:-1000} \
    "${MAVEN_CONFIG}"
    ;

# fix permissions
if [ -z "${MAVEN_SKIP_PERMFIX}" ]; # may become cumbersome if CONFIGDIR has large number of files
then
    vecho "Fixing permissions on $MAVEN_CONFIG files.";
    find ${MAVEN_CONFIG} \
        \! -user ${S6_USER:-alpine} -exec \
        chown --no-dereference \
        ${S6_USER:-alpine}:${PGID:-1000} \
        '{}' +;
fi;
