ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG MAVEN_VERSION="3.5.4"
ENV LANG=C.UTF-8 \
    M2_HOME=/usr/lib/mvn
#
RUN set -xe \
    && apk add -uU --no-cache curl openjdk8 tzdata \
    && curl -o /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
        -jkSL "https://www.apache.org/dist/maven/maven-${MAVEN_VERSION%%.*}/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz" \
    && tar -C /tmp -xzf /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && mv /tmp/apache-maven-${MAVEN_VERSION} ${M2_HOME} \
    && ln -s "$M2_HOME/bin/mvn" /usr/bin/mvn \
    && rm -rf /var/cache/apk/* /tmp/*
#
VOLUME /home/alpine/ /home/alpine/project/ # specify at runtime
#
USER alpine
#
WORKDIR /home/alpine/project/
#
ENTRYPOINT ["mvn"]
